### ISSUE TITLE
libbitcoin_server_a-init.o refusing to compile on ARMv7

### ISSUE THREAD

**Issue by ghost** [gandrewstone/bitcoin#147]
Hi,

I'm trying to compile from the git repo on my Odroid C1 (a bitnodes B1 device) but it won't progress beyond libbitcoin_server_a-init.o even after a number of hours.

**Comment by sickpig** [comment]
Never tried to compile natively on an ARM box, but I did cross compile successfully `bitcoind` for an AMR machine on a linux box. I followed the instructions you could find here: 
https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/0.12.1bu/doc/build-unix.md#arm-cross-compilation

You could find a little more info about the process here: 
https://infertux.com/posts/2016/02/23/cross-compile-bitcoin-for-arm/

**Comment by ghost** [comment]
Shame. I don't have any other Linux computers to compile on. Will have to stick with classic for now.

**Comment by ftrader** [comment]
@NanoAkron : are you able to see whether it maybe runs out of memory and starts to thrash around swapping?

You might be able to see using `vmstat 1` and observe 'so' column (swap out) for activity.

**Comment by sickpig** [comment]
@NanoAkon were you able to compile Classic binaries on the same machine where BU build failed?

**Comment by gandrewstone** [comment]
I am doing native compiles on a OrangePI plus machine.  One possibility: on embedded ARM machines, its important to enable a few GB of swap because they tend to have limited RAM, and compiling is RAM intensive.  And your swap disk needs to have reasonable performance -- this may be why you seem to be hanging.  The advantage of an OrangePI plus is that you can connect a SATA disk to it...

I'm closing this issue since the OP is not responding.
