### ISSUE TITLE
Bitcoin development

### ISSUE THREAD

**Issue by martketz** [gandrewstone/bitcoin#166]
Hi Everyone

I am looking for someone to help me create a bitcoin clone with the open source code that is available on github and obviously a few modifications.

Thanx

**Comment by ftrader** [comment]
The issue tracker of an existing Bitcoin client is a place to report issues or feature requests related to that software. "Help me create a Bitcoin clone" does not really fall under that category, which is why you won't get much constructive replies here.

Try some more general-purpose social media sites or Bitcoin forums (reddit.com/r/cryptocurrency , forum.bitcoin.com, bitco.in/forum, ...)
