### ISSUE TITLE
BUIP suggestion: trivial transaction replay protection 

### ISSUE THREAD

**Issue by BTCurious** [gandrewstone/bitcoin#389]
A smart way to do replay protection is to use the transaction version number in an unintended way. All non Bitcoin Unlimited wallets can upgrade to support the non-replayable transaction type by changing their transaction version to `2` to a `-1` in their creation code. This is only a few lines of code, is trivial for other wallets to support when they need it, and prevents blowback onto the old chain. 

* the transaction `version` field is a signed integer
* transactions >= version 2 are cleanly rejected without banning
* when a > 1MB block is seen, set a `isFork` flag on disk
* when `isFork` allow transactions with `-1` version number in blocks
* when `isFork` the wallet should use version `-1` for all new transactions
* optionally when `isFork` disallow version >0 transactions
* for future updates, decrease the version number further as Core can never use anything below 2

Is there interest in an implementation? The whole thing is probably only 15 LOC.

**Comment by BTCurious** [comment]
cc @zander

**Comment by zander** [comment]
> A smart way to do replay protection is to use the transaction version number in an unintended way

No, that won't work. Tx version number is not a consensus rule, it is a policy.

See a longer writeup here;
https://www.reddit.com/r/btc/comments/60pu0p/transaction_replay_what_is_it_and_what_should_we/

**Comment by BTCurious** [comment]
I don't see the problem with using the policy rules like this, Bitcoin Core doesn't relay or mine non-standard transactions so they'll by all purposes not appear in blocks made by it. You can even use this (modifying the policy) to make sure that only people mining for Bitcoin Unlimited blocks get fees from your transactions by changing the policy now, and requiring the version change it when `isFork` is set. If Core is having problems with replay by miners they just add a consensus rule requiring the version to be >0 and the protection is bulletproof. 

Don't let perfect be the enemy of good: easy to implement replay protection beats shed painting about it for months and ending up with none when its needed most.

**Comment by dgenr8** [comment]
Replay protection cannot take the form of requiring something to get transactions into the new chain.  This would require every wallet to upgrade to use the new chain.

TX version is also not suitable for _prevention_ of inclusion on the new chain, because being non-standard, such transactions will usually not be included on the old chain.

@gavinandresen suggests using presence of an OP_RETURN &lt;something> to prevent inclusion on the new chain.

Prevention of inclusion on the old chain is a bit trickier but some good thinking has been done by @ftrader.

**Comment by ftrader** [comment]
On the technical proposal at hand, I find the bolded part of this statement cannot be assured going into the future:

> for future updates, decrease the version number further **as Core can never use anything below 2**

This is one of the key criticisms of existing 'replay protection' schemes. They can be countered by hard forks which add compatibility to their particular signature validation requirements.
Case in point: Core could add support for such < 0 transaction versions (unless you believe Core will never hard fork - an argument which seems weak in light of recent events).

There are excellent arguments against adding replay protection of this kind to a Bitcoin implementation which wants to remain in consensus with the majority. It makes sense for implementations which want to diverge from consensus.

If one wanted to add trivial replay protection, a scheme like @jl777 's [1] would suffice, and even offer opt-in and support of multiple fork chains. An example of that has been implemented prototypically in [2] - the signature change parts of that are indeed not voluminous.
But I always find myself smiling when people only predict a small size of code change (e.g. 15 LOC), but neglect to estimate any testing impacts.

[1] https://steemit.com/bitcoin/@jl777/bitcoin-spinoff-fork-how-to-make-a-clean-fork-without-any-replay-attack-and-no-blockchain-visible-changes
[2] https://github.com/BTCfork/hardfork_prototype_1_mvf-bu/pull/67

**Comment by dgenr8** [comment]
"Replay protection" is a terrible name because the default must be to author transactions that are not prevented from being valid on any fork.

There's no point worrying about what the other guy can do with a hard fork.

**Comment by ftrader** [comment]
Right. On reflection, maybe "replay obstruction" would be a better term for it.

I do see a point for it if a minority wants to split off from a majority (e.g. as in the case of btcpowupdate.org) . They might want to transact their new token independently from Bitcoin so that the market could more easily find the value. As I stated, I don't think this applies to a Bitcoin implementation that simply strives to follow the majority consensus, which is what BU does afaik.

Then again, as long as a feature is entirely optional, I don't see a big problem implementing it (since it is always up to the users to make use of it). The default should remain as it you say: "_to author transactions that are not prevented from being valid on any fork._"

I don't see an opt-in being possible with this particular proposal though - other than not running the client entirely - please correct me if I'm wrong.

**Comment by sickpig** [comment]
closing, this turned into a "philosophical" convo more than an issue or a future request. Mind you I find the debate very useful but this is the right venue. What about mving to bitco.in/forum ?
