### ISSUE TITLE
1.0.1.4 banning lots of nodes?

### ISSUE THREAD

**Issue by patrikr** [gandrewstone/bitcoin#477]
1.0.1.4 seems to be banning lots of nodes, including other BU nodes. Example:

> 2017-04-26 15:55:29 Misbehaving: 70.176.191.136 (0 -> 100) BAN THRESHOLD EXCEEDED
> 2017-04-26 15:55:29 ERROR: Block 00000000000000000af05cfe87af7b655e223f373af147c773d1c3ad8ebf925c was never requested, banning peer=26
> 2017-04-26 15:55:29 ProcessMessages(block, 141410 bytes) FAILED peer=26

I added that node manually, it is a random BU node from bitnodes.21.co. (The block is from 2014 because this test node is that far behind.)

**Comment by sickpig** [comment]
The question is why  a peer should send you an header for a block from 2014 if your node is not requesting it? 

What was your node chaintip when you received such header?

**Comment by patrikr** [comment]
height=316558, two blocks past the one that caused the ban.

Here that block is added to the chain, 14 seconds earlier:

> 2017-04-26 15:55:15 UpdateTip: new best=00000000000000000af05cfe87af7b655e223f373af147c773d1c3ad8ebf925c  height=316556  log2_work=80.271675  tx=44932984  date=2014-08-20 02:04:45 progress=0.210611  cache=90.0MiB(57176tx)
> 2017-04-26 15:55:15 Acceptable block: ver:2 time:1408501121 size: 230929 Tx:483 Sig:1501

**Comment by ptschip** [comment]
due to the recent attacks we are getting more agressive at banning
misbehaving nodes...if you want to be absolutely sure not to ban a
specific node then you should whitelist that node.  Whitelisted nodes
cannot be banned.

to prevent a ban  add this to your startup or config:

whitelist=< ip> or <netmask> 


There are some nodes out there sending us un-requested blocks... and we
want to ban them... however there is also another intermittent issue
with a timer which can cause an occasional uncessesary ban which may be
what you are seeing also...I've patched that this morning and am testing
it now.

**Comment by sickpig** [comment]
@patrikr sorry I misunderstood your report. I somewhat thought that a node sent you an old header even if  your node wasn't catching up (IBD)

**Comment by sickpig** [comment]
closed by #506 on `release` and #479  on `dev` branch
