### ISSUE TITLE
Will there be a classic-like both-chains-at-the-same-time software?

### ISSUE THREAD

**Issue by DesWurstes** [gandrewstone/bitcoin#746]

**Comment by gandrewstone** [comment]
I've been fooling around with creating multiple chainstate databases.  However I don't like how using them simultaneously would mix the block data, and require quite a bit of CLI and GUI customization.  It seems like opportunities to accidentally make a payment on the wrong network would be large.  I'm more inclined to use this excuse to make a more robust block database for bitcoin cash blocks, and have 2 executables that can be run simultaneously using the same legacy block database for pre-fork blocks.  This works because the block database is append-only.
