### ISSUE TITLE
Balance is in BTC not BCC

### ISSUE THREAD

**Issue by Y2PM** [gandrewstone/bitcoin#758]
The currency is apparently in BTC not BCC or BCH in "Overview", "Send", "Receive" and "Transactions" tabs. In version v1.1.1.0-c0c02df.

**Comment by sickpig** [comment]
Just to be sure we are on the same page, you are talking about the label used in `bitcoin{d,-qt}` right?

We have a discussion in the past if it was the case of changing the unit to something else than BTC, but since that it wasn't clear what ticker the market would have been settled on we decide to postpone any decision. 

I guess that the time is come to take that decision, thou.

**Comment by Y2PM** [comment]
What's bitcoin{d,qt}? I mean in the GUI.

**Comment by sickpig** [comment]
Sorry for the confusing syntax, I meant `bitcoind` and `bitcoin-qt`

**Comment by php-wizard** [comment]
Hi,
i have BU Cash edition  v1.1.1.1-7d86d4e (64-bit).
The currency is displayed as BTC and not BCC.

How can i make sure it is connected to the right blockchain?

**Comment by ptschip** [comment]
this is fixed in the new release...we show units in BCH now.

**Comment by TTN-** [comment]
Time to close this issue?

**Comment by sickpig** [comment]
you are right, closing
