### ISSUE TITLE
Segregated witness.

### ISSUE THREAD

**Issue by gmaxwell** [gandrewstone/bitcoin#91]
Historically, forks of Bitcoin Core (such as Bitcoin Classic, and Bitcoin XT) have fallen far behind on updates to network consensus behavior.

I noticed that BU doesn't have a ticket to implement segwit and doesn't appear to have started on implementation.  The segwit proposal and consensus rules have been stable for six months now, and implementation in core is complete and getting the final little bit of preactivation tweaks and improvements. Segwit been active and testing well on testnet for months... so it's coming close to deployment time.

I'm interested in knowing BU's plans for SW implementation and deployment.

Segwit is specified in the following documents:

https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0145.mediawiki
and implemented in Bitcoin Core: bitcoin#8149

**Comment by rebroad** [comment]
@gmaxwell I think for BU to consider merging SegWit they would need to be of the belief that the fork will occur - what are your reasons for suspecting this will happen? It would be quite a bit of effort for nothing if the fork didn't happen.

**Comment by Alex-Linhares** [comment]
Perhaps it's best if untested (in-the-wild) vaporware is not included in BU for the foreseeable future.

**Comment by gmaxwell** [comment]
@Alex-Linhares Segwit has been deployed on testnet for something like four months now, and on development networks since something like December.

@rebroad virtually everything I've seen-- from list traffic, contact with hundreds of Bitcoin users and network participants suggests that people are very eager for many of the different improvements segwit brings. I expect it to activate very quickly. Perhaps it doesn't, that is up to the network-- and I don't really care one way or another but I really doubt that. I just don't want to see anyone left unnecessarily behind.

**Comment by Alex-Linhares** [comment]
@gmaxwell SegWit has no **battle-hardened** code running in the wild.  There has been zero incentive for hackers to break it.  

It's basic precautionary principle.

**Comment by ftrader** [comment]
@gmaxwell : I was trying to figure out the mainnet start time of the SegWit soft-fork, as I'm preparing some software that will be dependent on SegWit's activation parameters.

Looking at BIP141, I noticed the specification is incomplete - the mainnet start time still seems to be "TBD".
Is that correct?

**Comment by murchandamus** [comment]
@ftrader: As far as I understand, SegWit's mainnet start time will be provided with the release of 0.13.1.

**Comment by gmaxwell** [comment]
https://github.com/bitcoin/bips/commit/5c2da7e07d924c34af4edf7098981c9a376263d2

**Comment by rebroad** [comment]
It seems to me that ironically Unlimited's non-inclusion of SegWit so far may indirectly cause SegWit to not activate (due to ViaBTC mining using Unlimited) and thereby deny the entire bitcoin community the most immediately viable solution to the current scaling problem. If Bitcoin Unlimited is in favor of scaling bitcoin then surely they should not be blocking the best current hope (correct me if this assumption is wrong please) for bitcoin's expansion - this isn't mutually exclusive to increasing the block size - that can still happen in addition to SegWit - SegWit simply makes the usage of the blocks more efficient (i.e. more txs per MB), oh and eliminates the malleability vulnerability also.

**Comment by stefment** [comment]
If anyone is reading this i would like to request SegWit from Bitcoin Unlimited, else i will have to switch to core

**Comment by tenthirtyone** [comment]
What? BU wants to block segwit by refusing to include it in their code? That's outright hostility. Does BU want Bitcoin to fail? They shouldn't threaten the entire network with their tantrums. A lot of very good, hard work went in to segwit. If BU had a problem why have they not come forward with their concerns in the past two years? I think this is very anti-Bitcoin behavior that disrespects the decentralized spirit that Bitcoin embodies. 

Have these people even read the whitepaper? I don't think Satoshi intended for a small group of people in favor of centralization holding back this entire project.

**Comment by AndrewClifford** [comment]
@tenthirtyone This is not the place for rants. You are asked to take all your incorrect points to r/btc where you can be educated on the subject. 
For the record, BU does not have a position on SegWit. If it reaches majority support (nodes & hash-power) then it will be the subject of a BUIP and membership decision.
BU holds true to Satoshi's vision in his whitepaper which is why our membership considers a hard-fork to larger blocks sizes to be by far the most important improvement needed at the present time.

**Comment by ftrader** [comment]
Obligatory link to the whitepaper for those who wish to read it: https://bitcoin.com/bitcoin.pdf

**Comment by stefment** [comment]
Since when has r/btc educated anyone?

**Comment by tenthirtyone** [comment]
@AndrewClifford Don't censor me bro. I thought BU was all about freedom of speech. I think it's a serious problem if BU is going to ignore the voice of the community. 

Bitcoin Unlimited Exceptionalism does not stand. If overwhelming majority of the community agrees on Segwit an elite minority of Bitcoin Unlimited-only voting members should not be allowed to decide for the many.

**Comment by ftrader** [comment]
@tenthirtyone : looks like you're coming around to the notion of Nakamoto consensus.
Now, if you can persuade a majority of the Bitcoin community that SegWit is a good idea, your wishes will come true. Otherwise, perhaps you need to look at the criticisms instead, bro.

Have you considered creating a hard fork version of SegWit, with sufficient on-chain capacity increase and without economic discounts to incentivize non-existent layer 2 solutions, and putting it to the 95% test? Or, if you don't like 5% vetoes, have you considered submitting a BIP to Core to change BIP9?

P.S. having a hard time seeing how you're being [censored](https://en.wikipedia.org/wiki/Censorship)...

**Comment by rebroad** [comment]
@AndrewClifford How do you define "majority"? Currently SegWit does have the majority support by the miners, and the only thing holding it back from full support is Bitcoin Unlimited's non-inclusion of it in their code, which is being used by ViaBTC mining pool which is at 7% of the mining power, last I checked. So if I understand you correctly, you are presenting a "chicken and egg" situation where BU will include it only when BU has included it - a very indirect way to say "never".

**Comment by tenthirtyone** [comment]
@ftrader Your Red Herrings are interesting but just ignoring what I say won't make it magically go away.

Question: Why does an elite minority of the BU community get to decide for the the rest of the network? It would seem like this entire project is pointed toward social maneuvering to position BU where a small group of people like you can dictate to the rest of us. Why shouldn't we consider you a parasitic altcoin?

**Comment by ftrader** [comment]
> elite minority of the BU community

Anyone is free to apply to become a member of BU and vote on BUIPs. In contrast to Core the procedure is subject to voting by electronic signatures with a well-defined set of voting rules.

There is nothing elite in this, nor is it a privilege reserved for a minority of the BU community, nor is BU dictating anything to the community at large. So feel free to join up!

**Comment by tenthirtyone** [comment]
@ftrader When a specially privileged minority is able to force the majority their way it is elitism. You can deny the term, but your small group of self-imposed elites is blocking the majority. You can't change that with spin. This project's goal is apparently to debilitate Bitcoin and undermine the original project to bolster this perversion. 

We should fork BU off the network if it blocks segwit. Then you can play with your ball in your sandbox and you'll all be happy.

**Comment by dagurval** [comment]
@tenthirtyone Segwit has a self-imposed activation threshold on 95%. If you feel this is wrong, please nag the segwit implementers. You won't achieve anything here.

**Comment by tenthirtyone** [comment]
Where do I go to fork Bitcoin Unlimited and block your blocking of Segwit with a 5% minority?

**Comment by ftrader** [comment]
@tenthirtyone : You're on GitHub already, forking is what they do here.

But why not fork Core instead with a 5% minority? That way you can get what you want (SegWit) without having to wait.

**Comment by tuxayo** [comment]
@tenthirtyone Anyone can fork the code, the BU devs aren't forcing anybody to use BU as it is. Currently the miners that are mining with BU choose to vote for block increase and without SegWit.

If someone releases a fork with block increase and with SegWit, then the miners could choose to vote for that. But for now there doesn't seem to be enough interest in this choice (block increase + SegWit), that's why the miners keep mining BU without SegWit.

That's how mining consensus works, miners pick their client to vote for how they want the network to evolve.

**Comment by zeptochain** [comment]
FlexTrans seems a more elegant and appropriate solution to the issues that SegWit proposes to fix.

**Comment by juscamarena** [comment]
zeptochain: Are you sure? There's no support of FT ANYWHERE?

Alex-Linhares: BU sure is battle tested code, with two huge main net issues recently. Segwit is battle tested, and I continue to use it on testnet.

**Comment by sudo-ben** [comment]
@juscamarena FlexTrans is battle tested also. And if there is any unknown network messages there are many assert statements to provide feedback

**Comment by juscamarena** [comment]
@benjaminmcdonald nope. Has it been run on something valuable? Many have suggested that segwit to actually be tested be run on an altcoin. Is anyone bothering to run FT?

**Comment by earonesty** [comment]
FT is a vastly more complicated solution than segwit, but it seems like it might work if someone coded it up to meed more rigorous standards.   Few people object to FT in principle (flexible format, versioned, compressed).   The only objections I've seen are that it is really hard to do right and that the code is some developer-years from being deploy-able (a team of 6 could probably knock it out in 3-6 months).  No one would argue that something like FT isn't a desirable feature.   

I think sometimes people come across as bitchy online, when really they're just pointing out that code needs a lot of work before it can be included.   And other people come across as "arrogant" when really they are just, in a roundabout way maybe, asking for some help.

FT is fine.   But segwit gets us there sooner.   If BU had segwit... there would be no controversy anymore.   I mean.,..BU isn't really a fork anyway unless miners mine a fork.   And miners can mine a fork any time they want today.   

BU has some nice features that people might want to test out... but it shouldn't be at the expense of the rest of the network upgrading, that's all.   Including segwit support in BU wouldn't even change the code that much (4k lines i think?).   It's not *that much* tech debt.   Certainly not worth wrecking BU or Bitcoin over, is it?   

I would exclude the discount for witness too.   No need to support that in BU.

**Comment by zeptochain** [comment]
@earonesty SW as HF would be reasonable (as originally proposed). SW as SF isn't a great solution. I fully agree on eliminating the extras such as discount. 

Actually, (as you may know already) my views on managing the protocol are even more radical, as I have disclosed on medium.com, but the quest for specification and use of protocol buffers I mentioned therein do need a lot of investment of mindshare. 

I do believe that BU offers the best and most effective short-term solution. SW as SF needs much more buy-in from all clients rather than just a miner majority.

If you know anything about Bitcoin, then you will understand that the miners have (and will always have) the greatest self-interest in the value of the token.

**Comment by earonesty** [comment]
BU has no solution to malleability proposed, right?   Is there any even on the table?  Protobuf is like flextrans - tagged and versioned?

BU will be a hard fork anyway if the block size changes, so why not have an activation threshold for the first change (to prevent reorg issues), and put SW/HF activation in there too to prevent malleability bugs.   That's something more users could get behind.   I think Coinbase specifically wants this right?

The whole "miners have the greatest self interest" tangent is not strictly true if you are measuring by value and effort.   I would say at this point miners have a much smaller investment than users, by nearly any measure.   

Putting a malleability fix into BU would call Core's bluff.   Some users think BU exists solely to prevent malleability fixes.

**Comment by ftrader** [comment]
@earonesty : there is at least one proposal already: BUIP037

**Comment by afk11** [comment]
Most wallets aren't written in Core, they're written in other languages (javascript, python, etc). It's easier to implement a new script type than the new transaction format, plus it puts a vendor-specific burden on wallets/library maintainers. I liken it to Monero where they only had a CLI monerod at the start, and no other way to use the network.

Segwit as a soft-fork means all of these fixes are opt in and is something most libraries already support. 

FWIW - miners are free to remove the witness discount in stock SW, but that's similar to raising their fee rate above everyone else's. I wouldn't fret about it too much if the goal is to implement the feature segwit into both clients, because pools already know how to modify the software themselves.

**Comment by joshafest** [comment]
I think dynamic block size (size that change with transaction) will be good, so if we have fewer transaction we have smaller block size, and if we have large transitions we have large block size.
It can increase transitions/second ?

**Comment by sickpig** [comment]
fwiw BU have this BUIP proposing to implement SegWit as an hard fork, see: 
https://github.com/BitcoinUnlimited/BUIP/blob/master/037.mediawiki#Summary

closing, please reopen if you think it is appropriate.

**Comment by afk11** [comment]
@sickpig I've mentioned above that use of a feature is contingent on client libraries also supporting it. Is there something about hard-forks that makes them easier to get the likes of bcoin/bitcoinjs/bitcoin-php/python-bitcoinlib/bitcore to all implement the feature? 

No web wallet asks bitcoind to sign transactions for example, it's in clientside JS. Has there been any work on trying to build support for https://github.com/BitcoinUnlimited/BUIP/blob/master/037.mediawiki#Summary anywhere outside of BitcoinUnlimited?

**Comment by gmaxwell** [comment]
Segwit "implemented as a hardfork" is not segwit, it is radically incompatible and not just because it is a hardfork. It has no implementation, no testing, seems to have had no or next to no public design review.

This should be reopened but your repository will not permit me to do so.

You have failed to make good on your words above-- something like 90% of the the network has implemented segwit, and yet your membership has had no opportunity to choose it (not that I believe your little closed cabal would do so).  You say a lot about user choice, but you'll happily ignore what users are choosing when it doesn't fit your private orgs agenda.

**Comment by digitsu** [comment]
On the contrary, unlike the world where you get to dictate what you want
through forum winning posts, BU has a very clear set of governance rules
that it abides by. If you wish this to be reopened I suggest following the
procedure for doing so.

**Comment by juscamarena** [comment]
@digitsu what a great way to decide on software. I guess merit and user needs mean nothing to you? I am astonished BU still has inferior tech such as xThin, when they can merge in something solid like compact blocks....  BU's governance is one of its stupidest aspects, well one of many. You gotta wonder why you don't have a majority of users backing BU? Segwit signalling blocks are over 35% over the last 1k blocks, something you bet would never happen, do you not think users might want the choice to be segwit compatible?

**Comment by sickpig** [comment]
@gmaxwell 

This is the development issue tracker. Please use other media this kind of proposal.

That said you are welcome to submit a BUIP to propose the implementation of SegWit as a softfork for BU. Since you are not a BU member you should find a sponsor for your BUIP among BU members or apply to become one. If you'll be successful in proposing the BUIP, BU members will vote and if it will get accepted it will be implemented and included in BU.

Other then that as I already stated I think this discussion should happen in a more appropriate venue, e.g. bitco.in/forum. An issue tracker is not the best place where to discuss this kind of topic.

**Comment by digitsu** [comment]
Mr JCamerena, despite your efforts to change the BU rules by just "Trolling
harder" you too are free to open a BUIP through the same process as was
recommended to Gmax. Just because trolling harder works as a governance
model for core devs does not mean that your strategy will work here.  Those
are the rules and if you don't like them feel free to take your
conversation somewhere else.
(Or raise a BUIP to change them, though I figure if you won't go through
the trouble of doing so for Segwit you won't bother anyhow)

**Comment by juscamarena** [comment]
@digitsu you've been consistently wrong, but because I call them out I'm a troll? There have been various issues, that others have expressed implementation and design wise, I guess it's a lost cause, oh well.

**Comment by digitsu** [comment]
No, you are a troll because you have been told the procedure to follow but
you insist on trying to appeal to your cause by proselytizing on a
discussion forum instead of following them, indicating your true intent is
to simply foment drama instead of any real desire to effect constructive
change.

**Comment by juscamarena** [comment]
I've had discussions with other devs, logic doesn't seem to play much into what software gets merged in at all. Shifting from BU to Classic, I asked Zander why the hell he prefers xThin over Compact Blocks or kept it after all these issues, and he gave me the answer, the design is better, it's just implementation issues even if there's no spec.... What do I get in return? I get called a troll. The next day xThin had even more issues, due to DESIGN issues Greg pointed out earlier that were shrugged off coupled with stupid ban logic. At this point, it's just throwing shit at a wall no matter how bad and seeing if it sticks, no matter if there are superior solutions.

**Comment by sickpig** [comment]
@juscamarena @digitsu could you please move the discussion to another venue. Locking.
