### ISSUE TITLE
Can you please use your full name instead of "Bitcoin" ?

### ISSUE THREAD

**Issue by zander** [gandrewstone/bitcoin#92]
I noticed the merge of commit 37214f709c8747f3a04bee79e1fccdc60c691825 recently which renames many usages of "Bitcoin Core" to "Bitcoin" in GUI dialogs, logs and configure scripts.

Please refer in the software and in the sourcecode to Bitcoin Unlimited by its full name. I think it is a safe path to take in order to avoid even some feeling like you take ownership of the global brand name, we know thats not what you meant, but some may see it as such. Notice that Bitcoin is trademarked in parts of the world to avoid this, and I think we should set a good example.

Cheers!

**Comment by gandrewstone** [comment]
This is intentional.

Your trademark concern is generally worrisome but irrelevant to this issue since I can't sell "Apple XXXXX" technology devices without coming to an agreement with Apple.

"Bitcoin Unlimited" is plastered is prominent locations in the client -- there will be no confusion by the user what client s/he is running just because the word "Unlimited" is not placed in some error message or dialog box.

Not having to constantly rebrand these areas of the code will facilitate sharing across clients.
